;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Abilities.Aim",DevComment="")
+GameplayTagList=(Tag="Abilities.Shoot",DevComment="")
+GameplayTagList=(Tag="Gamedata.Aerodynamics",DevComment="")
+GameplayTagList=(Tag="Gamedata.BatteryCapacity",DevComment="")
+GameplayTagList=(Tag="Gamedata.MaxAcceleration",DevComment="")
+GameplayTagList=(Tag="Gamedata.MaxCapacity",DevComment="")
+GameplayTagList=(Tag="Gamedata.MaxSonarRange",DevComment="")
+GameplayTagList=(Tag="Gamedata.MaxSpeed",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Shot",DevComment="")
+GameplayTagList=(Tag="GameplayCue.ShotBig",DevComment="")

